[package]
name = "rust-argon2"
version = "0.5.1"
authors = ["Martijn Rijkeboer <mrr@sru-systems.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
description = "Rust implementation of the Argon2 password hashing function."
documentation = "https://docs.sru-systems.com/rust-argon2/0.5.0/argon2/"
homepage = "https://github.com/sru-systems/rust-argon2"
repository = "https://github.com/sru-systems/rust-argon2"
readme = "README.md"
keywords = ["argon2", "argon2d", "argon2i", "hash", "password"]

[lib]
name = "argon2"

[dependencies]
base64 = "0.10"
blake2b_simd = "0.5"
crossbeam-utils = "0.6"

[dev-dependencies]
hex = "0.3"
